'use client'

import { useState, useEffect, useRef, useCallback } from 'react'

export interface StoryboardScene {
  id: number
  label: string
  timeRange: string
  duration: number
  spokenLine: string
  onScreenText: string
  visualPrompt: string
  transition: string
}

interface Props {
  rawOutput: string
}

const GRADIENTS: Record<string, string> = {
  HOOK:      'from-red-600 via-rose-500 to-orange-500',
  LOOP:      'from-purple-700 via-violet-600 to-indigo-600',
  VALUE_1:   'from-blue-700 via-blue-600 to-cyan-600',
  VALUE_2:   'from-sky-600 via-cyan-500 to-blue-500',
  VALUE_3:   'from-teal-600 via-cyan-500 to-sky-600',
  INTERRUPT: 'from-amber-500 via-orange-500 to-yellow-500',
  CTA:       'from-emerald-600 via-teal-500 to-green-500',
}
const SCENE_EMOJI: Record<string, string> = {
  HOOK: '🪝', LOOP: '🔄', VALUE_1: '💡', VALUE_2: '💡', VALUE_3: '💡',
  INTERRUPT: '⚡', CTA: '📣',
}
function gradient(label: string) {
  return GRADIENTS[label] ?? 'from-slate-700 via-slate-600 to-slate-700'
}

// Coerce one raw JSON entry into a valid scene, defaulting missing/malformed
// fields so a single bad element never crashes the preview or the .srt export.
function coerceScene(raw: any, index: number): StoryboardScene | null {
  if (!raw || typeof raw !== 'object') return null
  const duration = Number(raw.duration)
  return {
    id: Number.isFinite(Number(raw.id)) ? Number(raw.id) : index + 1,
    label: typeof raw.label === 'string' && raw.label.trim() ? raw.label : `SCENE_${index + 1}`,
    timeRange: typeof raw.timeRange === 'string' ? raw.timeRange : '',
    duration: Number.isFinite(duration) && duration > 0 ? duration : 5,
    spokenLine: typeof raw.spokenLine === 'string' ? raw.spokenLine : '',
    onScreenText: typeof raw.onScreenText === 'string' ? raw.onScreenText : '',
    visualPrompt: typeof raw.visualPrompt === 'string' ? raw.visualPrompt : '',
    transition: typeof raw.transition === 'string' ? raw.transition : 'cut',
  }
}

export function parseScenes(raw: string): StoryboardScene[] | null {
  // Prefer the delimited block, but tolerate a missing closing marker (truncated output).
  const block = raw.match(/===SCENES===\s*([\s\S]*?)\s*===END_SCENES===/)?.[1]
    ?? raw.match(/===SCENES===\s*([\s\S]*)/)?.[1]
  if (!block) return null
  // Extract the JSON array even if it's wrapped in prose or code fences.
  const start = block.indexOf('[')
  const end = block.lastIndexOf(']')
  if (start === -1 || end === -1 || end <= start) return null
  try {
    const parsed = JSON.parse(block.slice(start, end + 1))
    if (!Array.isArray(parsed)) return null
    const scenes = parsed
      .map(coerceScene)
      .filter((s): s is StoryboardScene => s !== null)
    return scenes.length > 0 ? scenes : null
  } catch {
    return null
  }
}

// ─── Export helpers: turn scenes into formats video tools consume ───
function pad(n: number, len = 2) { return String(n).padStart(len, '0') }
function srtTime(totalSec: number): string {
  const h = Math.floor(totalSec / 3600)
  const m = Math.floor((totalSec % 3600) / 60)
  const s = Math.floor(totalSec % 60)
  return `${pad(h)}:${pad(m)}:${pad(s)},000`
}

export function buildScript(scenes: StoryboardScene[]): string {
  return scenes.map(s => s.spokenLine).join('\n\n')
}

export function buildSRT(scenes: StoryboardScene[]): string {
  let cursor = 0
  return scenes.map((s, i) => {
    const start = srtTime(cursor)
    cursor += s.duration
    const end = srtTime(cursor)
    return `${i + 1}\n${start} --> ${end}\n${s.onScreenText}`
  }).join('\n\n') + '\n'
}

export function buildVisualPrompts(scenes: StoryboardScene[]): string {
  return scenes.map((s, i) =>
    `${i + 1}. [${s.timeRange}] ${s.label.replace(/_/g, ' ')} — ${s.visualPrompt}`
  ).join('\n')
}

export function buildProductionKit(scenes: StoryboardScene[]): string {
  const total = scenes.reduce((a, s) => a + s.duration, 0)
  const header = `# Reel Production Kit\n\nTotal runtime: ${total}s · ${scenes.length} scenes\nGenerated by NavniAI — feed this into your video tool of choice.\n\n---\n`
  const body = scenes.map(s =>
    `## ${s.label.replace(/_/g, ' ')}  (${s.timeRange})\n\n` +
    `**🎙 Voiceover:** ${s.spokenLine}\n\n` +
    `**💬 On-screen caption:** ${s.onScreenText}\n\n` +
    `**📷 Visual / B-roll:** ${s.visualPrompt}\n\n` +
    `**🎬 Transition:** ${s.transition}\n`
  ).join('\n---\n\n')
  return `${header}\n${body}`
}

export default function StoryboardPreview({ rawOutput }: Props) {
  const scenes = parseScenes(rawOutput)
  const [activeIdx, setActiveIdx] = useState(0)
  const [isPlaying, setIsPlaying] = useState(false)
  const [progress, setProgress] = useState(0)
  const [copied, setCopied] = useState<string | null>(null)
  const timerRef   = useRef<ReturnType<typeof setTimeout> | null>(null)
  const intervalRef = useRef<ReturnType<typeof setInterval> | null>(null)

  const clearTimers = () => {
    if (timerRef.current)   clearTimeout(timerRef.current)
    if (intervalRef.current) clearInterval(intervalRef.current)
  }

  const flash = (key: string) => {
    setCopied(key)
    setTimeout(() => setCopied(c => (c === key ? null : c)), 2000)
  }
  const copy = (key: string, text: string) => {
    navigator.clipboard?.writeText(text).then(() => flash(key))
  }
  const download = (filename: string, text: string, mime: string) => {
    const blob = new Blob([text], { type: mime })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = filename
    a.click()
    URL.revokeObjectURL(url)
  }
  const shareKit = async (text: string) => {
    if (typeof navigator !== 'undefined' && navigator.share) {
      try { await navigator.share({ title: 'Reel Production Kit', text }) } catch { /* cancelled */ }
    } else {
      copy('share', text)
    }
  }

  useEffect(() => () => {
    clearTimers()
    if (typeof window !== 'undefined') window.speechSynthesis?.cancel()
  }, [])

  const playScene = useCallback((idx: number, list: StoryboardScene[]) => {
    if (idx >= list.length) { setIsPlaying(false); setProgress(0); return }
    const scene = list[idx]
    setActiveIdx(idx)
    setProgress(0)
    clearTimers()

    if (typeof window !== 'undefined' && 'speechSynthesis' in window) {
      window.speechSynthesis.cancel()
      const utt = new SpeechSynthesisUtterance(scene.spokenLine)
      utt.rate = 1.1
      window.speechSynthesis.speak(utt)
    }

    const ms = scene.duration * 1000
    let elapsed = 0
    intervalRef.current = setInterval(() => {
      elapsed += 80
      setProgress(Math.min((elapsed / ms) * 100, 100))
    }, 80)
    timerRef.current = setTimeout(() => {
      clearTimers()
      playScene(idx + 1, list)
    }, ms)
  }, [])

  const stopPlayback = useCallback(() => {
    clearTimers()
    if (typeof window !== 'undefined') window.speechSynthesis?.cancel()
    setIsPlaying(false)
    setProgress(0)
  }, [])

  const handlePlay = () => {
    if (!scenes) return
    if (isPlaying) { stopPlayback(); return }
    setIsPlaying(true)
    playScene(activeIdx, scenes)
  }

  const handleSceneClick = (idx: number) => {
    stopPlayback()
    setActiveIdx(idx)
  }

  if (!scenes) return null
  // Clamp: the parsed scene count can change (e.g. while output is still streaming),
  // so guard against a stale activeIdx pointing past the end of the list.
  const active = scenes[activeIdx] ?? scenes[0]
  const totalDuration = scenes.reduce((s, sc) => s + sc.duration, 0)

  return (
    <div className="border-b border-surface-300 bg-gradient-to-b from-surface-50/60 to-card/60 dark:from-surface-900/40 dark:to-card/40">
      {/* Header */}
      <div className="flex items-center justify-between px-4 py-2.5 border-b border-surface-200 dark:border-surface-700">
        <span className="text-[11px] font-semibold text-ink-700 flex items-center gap-1.5">
          🎞️ Reel Storyboard Preview
          <span className="text-[10px] text-ink-400 font-normal">· {totalDuration}s · {scenes.length} scenes</span>
        </span>
        <button
          onClick={handlePlay}
          className={`text-[11px] px-3 py-1 rounded-md font-semibold flex items-center gap-1 transition ${
            isPlaying
              ? 'bg-red-100 dark:bg-red-950 text-red-600 dark:text-red-400 hover:bg-red-200'
              : 'bg-gradient-to-r from-purple-600 to-indigo-600 text-white hover:from-purple-700 hover:to-indigo-700'
          }`}
        >
          {isPlaying ? '⏹ Stop' : '▶ Preview Reel'}
        </button>
      </div>

      <div className="flex gap-4 p-4">
        {/* Phone-shaped active scene card */}
        <div className="shrink-0">
          <div
            className={`relative w-32 sm:w-36 bg-gradient-to-b ${gradient(active.label)} rounded-2xl overflow-hidden shadow-lg`}
            style={{ aspectRatio: '9/16' }}
          >
            {/* Time badge */}
            <div className="absolute top-2 left-2 text-[8px] bg-black/40 text-white px-1.5 py-0.5 rounded-full font-mono">
              {active.timeRange}
            </div>
            {/* Transition badge */}
            <div className="absolute top-2 right-2 text-[7px] bg-white/20 text-white px-1 py-0.5 rounded font-mono uppercase tracking-wider">
              {active.transition}
            </div>
            {/* On-screen caption */}
            <div className="absolute inset-x-2 bottom-14 text-center">
              <p className="text-white font-black text-[9px] sm:text-[10px] leading-tight drop-shadow-lg uppercase tracking-wide">
                {active.onScreenText}
              </p>
            </div>
            {/* Scene label */}
            <div className="absolute bottom-3 inset-x-0 text-center">
              <span className="text-[8px] text-white/70 font-medium">
                {SCENE_EMOJI[active.label] ?? '🎬'} {active.label.replace(/_/g, ' ')}
              </span>
            </div>
            {/* Progress bar */}
            <div className="absolute bottom-0 inset-x-0 h-1 bg-black/30">
              <div
                className="h-full bg-white/80 transition-none"
                style={{ width: `${isPlaying ? progress : 0}%` }}
              />
            </div>
          </div>
          {/* Director note */}
          <p className="mt-2 w-32 sm:w-36 text-[9px] text-ink-400 italic leading-snug">
            📷 {active.visualPrompt}
          </p>
        </div>

        {/* Right side: voiceover + scene strip */}
        <div className="flex-1 min-w-0 flex flex-col gap-3">
          {/* Voiceover text */}
          <div className="p-3 bg-surface-100 dark:bg-surface-800 rounded-lg">
            <p className="text-[10px] text-ink-400 font-semibold mb-1">🎙 Voiceover</p>
            <p className="text-sm text-ink-700 dark:text-ink-200 leading-relaxed">{active.spokenLine}</p>
          </div>

          {/* Scene thumbnail strip */}
          <div className="flex gap-2 overflow-x-auto pb-1">
            {scenes.map((sc, i) => (
              <button
                key={sc.id}
                onClick={() => handleSceneClick(i)}
                title={sc.label.replace(/_/g, ' ')}
                className="shrink-0 flex flex-col items-center gap-1"
              >
                <div
                  className={`w-9 rounded-lg bg-gradient-to-b ${gradient(sc.label)} flex items-center justify-center border-2 transition-all ${
                    i === activeIdx
                      ? 'border-white shadow-md scale-110'
                      : 'border-transparent opacity-50 hover:opacity-80'
                  }`}
                  style={{ aspectRatio: '9/16' }}
                >
                  <span className="text-sm">{SCENE_EMOJI[sc.label] ?? '🎬'}</span>
                </div>
                <span className="text-[7px] text-ink-400 w-9 text-center leading-none truncate">
                  {sc.timeRange}
                </span>
              </button>
            ))}
          </div>
        </div>
      </div>

      {/* ── Export for video tools: NavniAI is the brain, render anywhere ── */}
      <div className="px-4 py-3 border-t border-surface-200 dark:border-surface-700">
        <p className="text-[10px] text-ink-400 font-semibold mb-2">
          📤 Feed your video tool — hand this production kit to InVideo, CapCut, Premiere, or any editor
        </p>
        <div className="flex flex-wrap gap-2">
          <button
            onClick={() => copy('script', buildScript(scenes))}
            className="text-[11px] px-2.5 py-1 rounded-md border border-surface-300 text-ink-600 hover:bg-surface-100 dark:hover:bg-surface-800 transition"
          >
            {copied === 'script' ? '✅ Copied' : '📝 Copy Voiceover Script'}
          </button>
          <button
            onClick={() => download('captions.srt', buildSRT(scenes), 'text/plain')}
            className="text-[11px] px-2.5 py-1 rounded-md border border-surface-300 text-ink-600 hover:bg-surface-100 dark:hover:bg-surface-800 transition"
          >
            💬 Download .srt Captions
          </button>
          <button
            onClick={() => copy('prompts', buildVisualPrompts(scenes))}
            className="text-[11px] px-2.5 py-1 rounded-md border border-surface-300 text-ink-600 hover:bg-surface-100 dark:hover:bg-surface-800 transition"
          >
            {copied === 'prompts' ? '✅ Copied' : '🎨 Copy Visual Prompts'}
          </button>
          <button
            onClick={() => download('reel-production-kit.md', buildProductionKit(scenes), 'text/markdown')}
            className="text-[11px] px-2.5 py-1 rounded-md bg-gradient-to-r from-purple-600 to-indigo-600 text-white hover:from-purple-700 hover:to-indigo-700 transition font-semibold"
          >
            📦 Download Production Kit
          </button>
          <button
            onClick={() => shareKit(buildProductionKit(scenes))}
            className="text-[11px] px-2.5 py-1 rounded-md border border-surface-300 text-ink-600 hover:bg-surface-100 dark:hover:bg-surface-800 transition"
          >
            {copied === 'share' ? '✅ Copied' : '📲 Share'}
          </button>
        </div>
      </div>
    </div>
  )
}
